# Generated by Django 3.1.2 on 2020-10-31 13:54

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('post', models.EmailField(max_length=254)),
                ('post_description', models.TextField()),
                ('post_digits', models.IntegerField(max_length=10, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('prof_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='hoodapp.profile')),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hood_name', models.CharField(max_length=60)),
                ('hood_location', models.CharField(max_length=60)),
                ('hood_pic', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='hood_pic')),
                ('hood_description', models.TextField()),
                ('occupant_count', models.IntegerField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('prof_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighbourhoods', to='hoodapp.profile')),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_name', models.CharField(max_length=60)),
                ('biz_email', models.EmailField(max_length=254)),
                ('biz_description', models.TextField()),
                ('biz_digits', models.IntegerField(max_length=10, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('hood_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='hoodapp.neighbourhood')),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
    ]
