# Generated by Django 3.1.2 on 2020-10-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0003_auto_20201031_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_digits',
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.TextField(),
        ),
    ]
