# Generated by Django 3.1.2 on 2020-10-31 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0004_auto_20201031_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hood_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='hoodapp.neighbourhood'),
        ),
    ]
