# Generated by Django 3.1.2 on 2020-10-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0005_post_hood_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_station', models.CharField(blank=True, max_length=60)),
                ('police_no', models.IntegerField(blank=True, verbose_name=10)),
                ('hospital_name', models.CharField(blank=True, max_length=60)),
                ('hospital_no', models.IntegerField(blank=True, verbose_name=10)),
                ('firedpt_name', models.CharField(blank=True, max_length=60)),
                ('firedpt_no', models.IntegerField(blank=True, verbose_name=10)),
            ],
        ),
        migrations.AlterField(
            model_name='business',
            name='biz_digits',
            field=models.IntegerField(null=True, verbose_name=10),
        ),
    ]
