# Generated by Django 3.1.2 on 2020-10-31 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0006_auto_20201031_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='hood_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='hoodapp.neighbourhood'),
        ),
        migrations.AlterField(
            model_name='business',
            name='biz_digits',
            field=models.IntegerField(null=True),
        ),
    ]
