# Generated by Django 3.1.2 on 2020-11-01 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0010_auto_20201101_0737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='occupant_count',
            new_name='family_size',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='hood_description',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='hood_pic',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hood_ref',
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='prof_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighbourhoods', to='hoodapp.profile'),
        ),
    ]
