# Generated by Django 3.1.2 on 2020-11-01 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0011_auto_20201101_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='hood_ref',
        ),
    ]
